"resource/loadingdialogbackground.res"
{
	"LoadingImage"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"LoadingImage"
		"xpos"				"0"
		"ypos"				"0"
		"wide"				"f-1"
		"tall"				"f-1"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"border"			"0"
		"image"				"img/bg"
		"scaleImage"		"1"
	}
	"Gradient"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"Gradient"
		"xpos"				"0"
		"ypos"				"0"
		"wide"				"400"
		"tall"				"85"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"border"			"0"
		"image"				"img/gradient"
		"scaleImage"		"1"
	}
	"Logo"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"Logo"
		"xpos"				"cs-0.5"
		"ypos"				"cs-0.5"
		"wide"				"256"
		"tall"				"256"
		"visible"			"1"
		"enabled"			"1"
		"tabPosition"		"0"
		"border"			"0"
		"image"				"hl2sbpp"
		"scaleImage"		"1"
	}
	"ServerName"
	{
		"ControlName"		"Label"
		"fieldName"			"ServerName"
		"xpos"				"0"
		"ypos"				"0"
		"wide"				"400"
		"tall"				"1"
		"visible"			"1"
		"enabled"			"1"
		"zpos"          	"2"
		"fgcolor"       	"255 255 255 255"
        "text" 				"Server Name Goes Here"
		"proportionalToParent" "1"
	}
	"MapName"
	{
		"ControlName"		"Label"
		"fieldName"			"MapName"
		"xpos"				"0"
		"ypos"				"0"
		"wide"				"400"
		"tall"				"1"
		"visible"			"1"
		"enabled"			"1"
		"zpos"          	"2"
		"fgcolor"       	"255 255 255 255"
        "text" 				"Map Name Goes Here"
		"proportionalToParent" "1"
	}
	"GameMode"
	{
		"ControlName"		"Label"
		"fieldName"			"GameMode"
		"xpos"				"0"
		"ypos"				"0"
		"wide"				"400"
		"tall"				"1"
		"visible"			"1"
		"enabled"			"1"
		"zpos"          	"2"
		"fgcolor"       	"255 255 255 255"
        "text" 				"GameMode Goes Here"
		"proportionalToParent" "1"
	}
	"MapIcon"
	{
		"ControlName"		"ImagePanel"
		"fieldName"			"MapIcon"
		"xpos"				"10"
		"ypos"				"10"
		"wide"				"64"
		"tall"				"64"
		"visible"			"1"
		"enabled"			"1"
		"border"			"0"
		"image"				"img/noicon"
	}
}