"Entities"
{
	"page_icon"	"materials/icon16/sport_8ball.png"

	"header"
	{
		"text" "Ammo And Stuff"
	}

    "image_button"
    {
        "name" "Strider Buster"
        "image" "materials/entities/weapon_striderbuster.png"
        "command" "ent_create weapon_striderbuster"
    }

	"image_button"
	{
		"name" "Pistol Ammo"
		"image" "materials/entities/item_ammo_pistol.png"
		"command" "ent_create item_ammo_pistol"
	}

	"image_button"
	{
		"name" "Pistol Ammo (Large)"
		"image" "materials/entities/item_ammo_pistol_large.png"
		"command" "ent_create item_ammo_pistol_large"
	}

	"image_button"
	{
		"name" "SMG1 Ammo"
		"image" "materials/entities/item_ammo_smg1.png"
		"command" "ent_create item_ammo_smg1"
	}

	"image_button"
	{
		"name" "SMG1 Ammo (Large)"
		"image" "materials/entities/item_ammo_smg1_large.png"
		"command" "ent_create item_ammo_smg1_large"
	}

	"image_button"
	{
		"name" "Shotgun Ammo"
		"image" "materials/entities/ammo_buckshot.png"
		"command" "ent_create item_box_buckshot"
	}

	"image_button"
	{
		"name" "AR2 Ammo"
		"image" "materials/entities/item_ammo_ar2.png"
		"command" "ent_create item_ammo_ar2"
	}

	"image_button"
	{
		"name" "AR2 Ammo (Large)"
		"image" "materials/entities/item_ammo_ar2_large.png"
		"command" "ent_create item_ammo_ar2_large"
	}

	"image_button"
	{
		"name" ".357 Ammo"
		"image" "materials/entities/item_ammo_357.png"
		"command" "ent_create item_ammo_357"
	}

	"image_button"
	{
		"name" ".357 Ammo (Large)"
		"image" "materials/entities/item_ammo_357_large.png"
		"command" "ent_create item_ammo_357_large"
	}

	"image_button"
	{
		"name" "Crossbow Bolts"
		"image" "materials/entities/item_ammo_crossbow.png"
		"command" "ent_create item_ammo_crossbow"
	}

	"image_button"
	{
		"name" "RPG Round"
		"image" "materials/entities/item_rpg_round.png"
		"command" "ent_create item_rpg_round"
	}

	"image_button"
	{
		"name" "SMG1 Grenade"
		"image" "materials/entities/item_ammo_smg1_grenade.png"
		"command" "ent_create item_ammo_smg1_grenade"
	}

	"image_button"
	{
		"name" "Combine Balls"
		"image" "materials/entities/item_ammo_ar2_altfire.png"
		"command" "ent_create item_ammo_ar2_altfire"
	}

	"header"
	{
		"text" "Vehicles"
	}

    "image_button"
    {
        "name" "Jeep"
        "image" "materials/entities/jeep.png"
        "command" "ch_createjeep"
    }

    "image_button"
    {
        "name" "Airboat"
        "image" "materials/entities/airboat.png"
        "command" "ch_createairboat; ent_setname airboatwithgun; ent_fire airboatwithgun enablegun 1"
    }

    "image_button"
    {
        "name" "Jalopy"
        "image" "materials/entities/jalopy.png"
        "command" "ch_createjalopy"
    }

    "image_button"
    {
        "name" "Pod"
        "image" "materials/entities/pod.png"
        "command" "ch_createpod"
    }

    "image_button"
    {
        "name" "Chair"
        "image" "materials/entities/chair_wood.png"
        "command" "ent_create prop_vehicle_chair"
    }

	"header"
	{
		"text" "Weapons"
	}

    "image_button"
    {
        "name" "Stunstick"
        "image" "materials/entities/weapon_stunstick.png"
        "command" "give weapon_stunstick"
    }

    "image_button"
    {
        "name" "Pistol"
        "image" "materials/entities/weapon_pistol.png"
        "command" "give weapon_pistol"
    }

    "image_button"
    {
        "name" ".357 Magnum"
        "image" "materials/entities/weapon_357.png"
        "command" "give weapon_357"
    }

    "image_button"
    {
        "name" "Grenade"
        "image" "materials/entities/weapon_frag.png"
        "command" "give weapon_frag"
    }

    "image_button"
    {
        "name" "Bugbait"
        "image" "materials/entities/weapon_bugbait.png"
        "command" "give weapon_bugbait"
    }

    "image_button"
    {
        "name" "SLAM"
        "image" "materials/entities/weapon_slam.png"
        "command" "give weapon_slam"
    }

    "image_button"
    {
        "name" "Crossbow"
        "image" "materials/entities/weapon_crossbow.png"
        "command" "give weapon_crossbow"
    }

    "image_button"
    {
        "name" "SMG1"
        "image" "materials/entities/weapon_smg1.png"
        "command" "give weapon_smg1"
    }

    "image_button"
    {
        "name" "Shotgun"
        "image" "materials/entities/weapon_shotgun.png"
        "command" "give weapon_shotgun"
    }

    "image_button"
    {
        "name" "RPG"
        "image" "materials/entities/weapon_rpg.png"
        "command" "give weapon_rpg"
    }

    "image_button"
    {
        "name" "AR2"
        "image" "materials/entities/weapon_ar2.png"
        "command" "give weapon_ar2"
    }

    "image_button"
    {
        "name" "Gravity Gun"
        "image" "materials/entities/weapon_physcannon.png"
        "command" "give weapon_physcannon"
    }

    "image_button"
    {
        "name" "Physics Gun"
        "image" "materials/entities/weapon_physgun.png"
        "command" "give weapon_physgun"
    }

    "image_button"
    {
        "name" "Toolgun"
        "image" "materials/entities/gmod_tool.png"
        "command" "give weapon_toolgun"
    }

    "image_button"
    {
        "name" "Camera"
        "image" "materials/entities/gmod_camera.png"
        "command" "give weapon_camera"
    }

    "image_button"
    {
        "name" "Fists"
        "image" "materials/entities/weapon_fists.png"
        "command" "give weapon_fists"
    }

    "image_button"
    {
        "name" "Crowbar"
        "image" "materials/entities/weapon_crowbar.png"
        "command" "give weapon_crowbar"
    }

    "image_button"
    {
        "name" "Flechette Gun (EP2)"
        "image" "materials/entities/weapon_flechettegun.png"
        "command" "give weapon_flechettegun"
    }

	"header"
	{
		"text" "SB++"
	}

    "image_button"
    {
        "name" "Light"
        "image" "materials/entities/misc/light.png"
        "command" "ent_create prop_light"
    }

    "image_button"
    {
        "name" "Balloon"
        "image" "materials/entities/misc/balloon.png"
        "command" "ent_create prop_balloon"
    }

    "image_button"
    {
        "name" "Ball"
        "image" "materials/entities/sent_ball.png"
        "command" "ent_create prop_ball"
    }

	"header"
	{
		"text" "HL:S Weapons"
	}

    "image_button"
    {
        "name" "Crowbar (HL1)"
        "image" "materials/entities/weapon_crowbar_hl1.png"
        "command" "give weapon_crowbar_hl1"
    }

    "image_button"
    {
        "name" "9mm Handgun (HL1)"
        "image" "materials/entities/weapon_glock_hl1.png"
        "command" "give weapon_glock_hl1"
    }

    "image_button"
    {
        "name" ".357 (HL1)"
        "image" "materials/entities/weapon_357_hl1.png"
        "command" "give weapon_357_hl1"
    }

    "image_button"
    {
        "name" "Shotgun (HL1)"
        "image" "materials/entities/weapon_shotgun_hl1.png"
        "command" "give weapon_shotgun_hl1"
    }

    "image_button"
    {
        "name" "Crossbow (HL1)"
        "image" "materials/entities/weapon_crossbow_hl1.png"
        "command" "give weapon_crossbow_hl1"
    }

    "image_button"
    {
        "name" "RPG (HL1)"
        "image" "materials/entities/weapon_rpg_hl1.png"
        "command" "give weapon_rpg_hl1"
    }

    "image_button"
    {
        "name" "Tau Cannon (HL1)"
        "image" "materials/entities/weapon_gauss.png"
        "command" "give weapon_gauss_hl1"
    }

    "image_button"
    {
        "name" "Gluon Gun (Egon) (HL1)"
        "image" "materials/entities/weapon_egon.png"
        "command" "give weapon_egon_hl1"
    }

    "image_button"
    {
        "name" "Hivehand (Hornet Gun) (HL1)"
        "image" "materials/entities/weapon_hornetgun.png"
        "command" "give weapon_hornetgun_hl1"
    }

    "image_button"
    {
        "name" "Hand Grenade (HL1)"
        "image" "materials/entities/weapon_handgrenade.png"
        "command" "give weapon_handgrenade_hl1"
    }

    "image_button"
    {
        "name" "Satchel (HL1)"
        "image" "materials/entities/weapon_satchel.png"
        "command" "give weapon_satchel_hl1"
    }

    "image_button"
    {
        "name" "Tripmine (HL1)"
        "image" "materials/entities/weapon_tripmine.png"
        "command" "give weapon_tripmine_hl1"
    }

    "image_button"
    {
        "name" "Snark (HL1)"
        "image" "materials/entities/weapon_snark.png"
        "command" "give weapon_snark_hl1"
    }

}