"Misc"
{
	"page_icon"	"materials/icon16/page_white_gear.png"

	"header"
	{
		"text" "Utilities"
	}

    "image_button"
    {
        "name" "0.5x Speed"
        "image" "materials/entities/misc/x1.png"
        "command" "host_timescale 0.5"
    }

    "image_button"
    {
        "name" "1x Speed"
        "image" "materials/entities/misc/x1.png"
        "command" "host_timescale 1"
    }

    "image_button"
    {
        "name" "2x Speed"
        "image" "materials/entities/misc/x2.png"
        "command" "host_timescale 2"
    }

    "image_button"
    {
        "name" "Thirdperson"
        "image" "materials/entities/misc/third.png"
        "command" "thirdperson"
    }

    "image_button"
    {
        "name" "Firstperson"
        "image" "materials/entities/misc/first.png"
        "command" "firstperson"
    }

	"header"
	{
		"text" "Quick Messages"
	}

    "image_button"
    {
        "name" "Thanks"
        "image" "materials/entities/message.png"
        "command" "say Thanks"
    }

    "image_button"
    {
        "name" "Help"
        "image" "materials/entities/message.png"
        "command" "say Help"
    }

    "image_button"
    {
        "name" "No"
        "image" "materials/entities/message.png"
        "command" "say No"
    }

    "image_button"
    {
        "name" "Yes"
        "image" "materials/entities/message.png"
        "command" "say Yes"
    }

    "image_button"
    {
        "name" "OK"
        "image" "materials/entities/message.png"
        "command" "say OK"
    }

    "image_button"
    {
        "name" "Hello"
        "image" "materials/entities/message.png"
        "command" "say Hello"
    }

    "image_button"
    {
        "name" "Stop"
        "image" "materials/entities/message.png"
        "command" "say Stop"
    }

    "image_button"
    {
        "name" "Start"
        "image" "materials/entities/message.png"
        "command" "say Start"
    }

	"header"
	{
		"text" "Movement"
	}

    "image_button"
    {
        "name" "2004 Movement"
        "image" "materials/entities/misc/x2.png"
        "command" "toggle mov_2004"
    }

    "image_button"
    {
        "name" "Accelerated Fast Hopping"
        "image" "materials/entities/misc/move.png"
        "command" "toggle mov_afh"
    }

	"header"
	{
		"text" "Props"
	}

    "image_button"
    {
        "name" "Light"
        "image" "materials/entities/misc/light.png"
        "command" "ent_create prop_light"
    }

    "image_button"
    {
        "name" "Balloon"
        "image" "materials/entities/misc/balloon.png"
        "command" "ent_create prop_balloon"
    }

	"header"
	{
		"text" "Development Stuff"
	}

    "image_button"
    {
        "name" "Developer Mode"
        "image" "materials/entities/.png"
        "command" "toggle developer"
    }


    "image_button"
    {
        "name" "Hint Test"
        "image" "materials/entities/.png"
        "command" "hint_add Test 5"
    }

    "image_button"
    {
        "name" "Allow Clientside Lua"
        "image" "materials/entities/.png"
        "command" "toggle sv_clientside_lua_allowed"
    }

	"header"
	{
		"text" "Cheats"
	}

    "image_button"
    {
        "name" "Cheats (toggle)"
        "image" "materials/entities/.png"
        "command" "toggle sv_cheats"
    }

    "image_button"
    {
        "name" "Godmode"
        "image" "materials/entities/.png"
        "command" "god"
    }

    "image_button"
    {
        "name" "Buddha"
        "image" "materials/entities/.png"
        "command" "buddha"
    }

    "image_button"
    {
        "name" "No Target"
        "image" "materials/entities/.png"
        "command" "notarget"
    }

    "image_button"
    {
        "name" "Give all weapons"
        "image" "materials/entities/.png"
        "command" "impulse 101"
    }

    "image_button"
    {
        "name" "Disable/Enable AI"
        "image" "materials/entities/.png"
        "command" "ai_disable"
    }

    "image_button"
    {
        "name" "Fullbright (toggle)"
        "image" "materials/entities/.png"
        "command" "toggle mat_fullbright"
    }

}