"NPCs"
{
	"page_icon"	"images/folder_database.png"

	"header"
	{
		"text" "Main Characters"
	}

    "image_button"
    {
        "name" "Alyx"
        "image" "materials/entities/npc_alyx.png"
        "command" "npc_create npc_alyx"
    }

    "image_button"
    {
        "name" "Kleiner"
        "image" "materials/entities/npc_kleiner.png"
        "command" "npc_create npc_kleiner"
    }

    "image_button"
    {
        "name" "GMan"
        "image" "materials/entities/npc_gman.png"
        "command" "npc_create npc_gman"
    }

    "image_button"
    {
        "name" "Breen"
        "image" "materials/entities/npc_breen.png"
        "command" "npc_create npc_breen"
    }

    "image_button"
    {
        "name" "Eli"
        "image" "materials/entities/npc_eli.png"
        "command" "npc_create npc_eli"
    }

    "image_button"
    {
        "name" "Mossman"
        "image" "materials/entities/npc_mossman.png"
        "command" "npc_create npc_mossman"
    }

    "image_button"
    {
        "name" "DOG"
        "image" "materials/entities/npc_dog.png"
        "command" "npc_create npc_dog"
    }

    "image_button"
    {
        "name" "Barney"
        "image" "materials/entities/npc_barney.png"
        "command" "npc_create npc_barney"
    }

    "image_button"
    {
        "name" "Vortigaunt"
        "image" "materials/entities/npc_vortigaunt.png"
        "command" "npc_create npc_vortigaunt"
    }

    "image_button"
    {
        "name" "Magnusson (EP2)"
        "image" "materials/entities/npc_magnusson.png"
        "command" "npc_create npc_magnusson"
    }

	"header"
	{
		"text" "The Undead/Aliens"
	}

    "image_button"
    {
        "name" "Barnacle"
        "image" "materials/entities/npc_barnacle.png"
        "command" "npc_create npc_barnacle"
    }

    "image_button"
    {
        "name" "Ichthyosaur"
        "image" "materials/entities/npc_ichthyosaur.png"
        "command" "npc_create npc_ichthyosaur"
    }

    "image_button"
    {
        "name" "Antlion"
        "image" "materials/entities/npc_antlion.png"
        "command" "npc_create npc_antlion"
    }

    "image_button"
    {
        "name" "Antlion Guard"
        "image" "materials/entities/npc_antlionguard.png"
        "command" "npc_create npc_antlionguard"
    }

    "image_button"
    {
        "name" "Headcrab"
        "image" "materials/entities/npc_headcrab.png"
        "command" "npc_create npc_headcrab"
    }

    "image_button"
    {
        "name" "Fast Headcrab"
        "image" "materials/entities/npc_headcrab_fast.png"
        "command" "npc_create npc_fastheadcrab"
    }

    "image_button"
    {
        "name" "Poison Headcrab"
        "image" "materials/entities/npc_headcrab_black.png"
        "command" "npc_create npc_headcrab_poison"
    }

    "image_button"
    {
        "name" "Zombie"
        "image" "materials/entities/npc_zombie.png"
        "command" "npc_create npc_zombie"
    }

    "image_button"
    {
        "name" "Fast Zombie"
        "image" "materials/entities/npc_fastzombie.png"
        "command" "npc_create npc_fastzombie"
    }

    "image_button"
    {
        "name" "Fast Zombie Torso"
        "image" "materials/entities/npc_fastzombie_torso.png"
        "command" "npc_create npc_fastzombie_torso"
    }

    "image_button"
    {
        "name" "Poison Zombie"
        "image" "materials/entities/npc_poisonzombie.png"
        "command" "npc_create npc_poisonzombie"
    }

    "image_button"
    {
        "name" "Zombie Torso"
        "image" "materials/entities/npc_zombie_torso.png"
        "command" "npc_create npc_zombie_torso"
    }

    "image_button"
    {
        "name" "Zombine (EP2)"
        "image" "materials/entities/npc_zombine.png"
        "command" "npc_create npc_zombine"
    }

	"header"
	{
		"text" "Humans"
	}

    "image_button"
    {
        "name" "Fisherman (Lost Coast)"
        "image" "materials/entities/npc_fisherman.png"
        "command" "npc_create npc_fisherman"
    }

    "image_button"
    {
        "name" "Citizen"
        "image" "materials/entities/npc_citizen.png"
        "command" "npc_create npc_citizen"
    }

    "image_button"
    {
        "name" "Refugee"
        "image" "materials/entities/refugee.png"
        "command" "ent_create npc_citizen citizentype 2"
    }

    "image_button"
    {
        "name" "Rebel"
        "image" "materials/entities/rebel.png"
        "command" "ent_create npc_citizen citizentype 3"
    }

	"header"
	{
		"text" "The Combine"
	}

    "image_button"
    {
        "name" "Metrocop"
        "image" "materials/entities/npc_metropolice.png"
        "command" "npc_create npc_metropolice"
    }

	"image_button"
    {
        "name" "Stalker"
        "image" "materials/entities/npc_stalker.png"
        "command" "npc_create npc_stalker"
    }

    "image_button"
    {
        "name" "Combine Soldier"
        "image" "materials/entities/npc_combine_s.png"
        "command" "npc_create npc_combine_s"
    }

    "image_button"
    {
        "name" "Elite Combine Soldier"
        "image" "materials/entities/combineelite.png"
        "command" "ent_create npc_combine_s model models/Combine_Super_Soldier.mdl tacticalvariant 2 NumGrenades 2"
    }

    "image_button"
    {
        "name" "Nova Prospekt Guard"
        "image" "materials/entities/combineprison.png"
        "command" "ent_create npc_combine_s model models/Combine_Soldier_PrisonGuard.mdl NumGrenades 2"
    }

    "image_button"
    {
        "name" "Manhack"
        "image" "materials/entities/npc_manhack.png"
        "command" "npc_create npc_manhack"
    }

    "image_button"
    {
        "name" "City Scanner"
        "image" "materials/entities/npc_cscanner.png"
        "command" "npc_create npc_cscanner"
    }

    "image_button"
    {
        "name" "Claw Scanner"
        "image" "materials/entities/npc_clawscanner.png"
        "command" "npc_create npc_clawscanner"
    }

    "image_button"
    {
        "name" "Rollermine"
        "image" "materials/entities/npc_rollermine.png"
        "command" "npc_create npc_rollermine"
    }

    "image_button"
    {
        "name" "Hunter (EP2)"
        "image" "materials/entities/npc_hunter.png"
        "command" "npc_create npc_hunter"
    }

    "image_button"
    {
        "name" "Combine Mine"
        "image" "materials/entities/combine_mine.png"
        "command" "ent_create combine_mine"
    }

    "image_button"
    {
        "name" "Advisor"
        "image" "materials/entities/npc_advisor.png"
        "command" "npc_create npc_advisor"
    }

    "image_button"
    {
        "name" "Gunship"
        "image" "materials/entities/npc_combinegunship.png"
        "command" "give npc_combinegunship"
    }

    "image_button"
    {
        "name" "Helicopter"
        "image" "materials/entities/npc_helicopter.png"
        "command" "give npc_helicopter"
    }

    "image_button"
    {
        "name" "Strider"
        "image" "materials/entities/npc_strider.png"
        "command" "give npc_strider"
    }

	"header"
	{
		"text" "Birds"
	}

    "image_button"
    {
        "name" "Grigori"
        "image" "materials/entities/npc_monk.png"
        "command" "npc_create npc_monk"
    }

    "image_button"
    {
        "name" "Seagull"
        "image" "materials/entities/npc_seagull.png"
        "command" "npc_create npc_seagull"
    }

    "image_button"
    {
        "name" "Pigeon"
        "image" "materials/entities/npc_pigeon.png"
        "command" "npc_create npc_pigeon"
    }

    "image_button"
    {
        "name" "Crow"
        "image" "materials/entities/npc_crow.png"
        "command" "npc_create npc_crow"
    }

	"header"
	{
		"text" "NPC Weapons"
	}

    "image_button"
    {
        "name" "None"
        "image" ""
        "command" "npc_create_equipment weapon_none"
    }

    "image_button"
    {
        "name" "Stunstick"
        "image" "materials/entities/weapon_stunstick.png"
        "command" "npc_create_equipment weapon_stunstick"
    }

    "image_button"
    {
        "name" "Pistol"
        "image" "materials/entities/weapon_pistol.png"
        "command" "npc_create_equipment weapon_pistol"
    }

    "image_button"
    {
        "name" "SMG1"
        "image" "materials/entities/weapon_smg1.png"
        "command" "npc_create_equipment weapon_smg1"
    }

    "image_button"
    {
        "name" "Shotgun"
        "image" "materials/entities/weapon_shotgun.png"
        "command" "npc_create_equipment weapon_shotgun"
    }

    "image_button"
    {
        "name" "RPG"
        "image" "materials/entities/weapon_rpg.png"
        "command" "npc_create_equipment weapon_rpg"
    }

    "image_button"
    {
        "name" "AR2"
        "image" "materials/entities/weapon_ar2.png"
        "command" "npc_create_equipment weapon_ar2"
    }

	"header"
	{
		"text" "Half-Life: Source"
	}

    "image_button"
    {
        "name" "Alien Grunt (HL1)"
        "image" "materials/entities/monster_alien_grunt.png"
        "command" "npc_create monster_alien_grunt"
    }

    "image_button"
    {
        "name" "Alien Slave (HL1)"
        "image" "materials/entities/monster_alien_slave.png"
        "command" "npc_create monster_alien_slave"
    }

    "image_button"
    {
        "name" "Apache (HL1)"
        "image" "materials/entities/monster_apache.png"
        "command" "npc_create monster_apache"
    }

    "image_button"
    {
        "name" "Babycrab (HL1)"
        "image" "materials/entities/monster_babycrab.png"
        "command" "npc_create monster_babycrab"
    }

    "image_button"
    {
        "name" "Barnacle (HL1)"
        "image" "materials/entities/monster_barnacle.png"
        "command" "npc_create monster_barnacle"
    }

    "image_button"
    {
        "name" "Barney (HL1)"
        "image" "materials/entities/monster_barney.png"
        "command" "npc_create monster_barney"
    }

    "image_button"
    {
        "name" "Big Momma (HL1)"
        "image" "materials/entities/monster_bigmomma.png"
        "command" "npc_create monster_bigmomma"
    }

    "image_button"
    {
        "name" "Bloater (HL1)"
        "image" "materials/entities/monster_bloater.png"
        "command" "npc_create monster_bloater"
    }

    "image_button"
    {
        "name" "Bullchicken (HL1)"
        "image" "materials/entities/monster_bullchicken.png"
        "command" "npc_create monster_bullchicken"
    }

    "image_button"
    {
        "name" "Cockroach (HL1)"
        "image" "materials/entities/monster_cockroach.png"
        "command" "npc_create monster_cockroach"
    }

    "image_button"
    {
        "name" "Flyer (HL1)"
        "image" "materials/entities/monster_flyer.png"
        "command" "npc_create monster_flyer"
    }

    "image_button"
    {
        "name" "Flyer Flock (HL1)"
        "image" "materials/entities/monster_flyer_flock.png"
        "command" "npc_create monster_flyer_flock"
    }

    "image_button"
    {
        "name" "Furniture (HL1)"
        "image" "materials/entities/monster_furniture.png"
        "command" "npc_create monster_furniture"
    }

    "image_button"
    {
        "name" "Gargantua (HL1)"
        "image" "materials/entities/monster_gargantua.png"
        "command" "npc_create monster_gargantua"
    }

    "image_button"
    {
        "name" "Generic (HL1)"
        "image" "materials/entities/monster_generic.png"
        "command" "npc_create monster_generic"
    }

    "image_button"
    {
        "name" "G-Man (HL1)"
        "image" "materials/entities/monster_gman.png"
        "command" "npc_create monster_gman"
    }

    "image_button"
    {
        "name" "Grunt Repel (HL1)"
        "image" "materials/entities/monster_grunt_repel.png"
        "command" "npc_create monster_grunt_repel"
    }

    "image_button"
    {
        "name" "Headcrab (HL1)"
        "image" "materials/entities/monster_headcrab.png"
        "command" "npc_create monster_headcrab"
    }

    "image_button"
    {
        "name" "Houndeye (HL1)"
        "image" "materials/entities/monster_houndeye.png"
        "command" "npc_create monster_houndeye"
    }

    "image_button"
    {
        "name" "Human Assassin (HL1)"
        "image" "materials/entities/monster_human_assassin.png"
        "command" "npc_create monster_human_assassin"
    }

    "image_button"
    {
        "name" "Human Grunt (HL1)"
        "image" "materials/entities/monster_human_grunt.png"
        "command" "npc_create monster_human_grunt"
    }

    "image_button"
    {
        "name" "Ichthyosaur (HL1)"
        "image" "materials/entities/monster_ichthyosaur.png"
        "command" "npc_create monster_ichthyosaur"
    }

    "image_button"
    {
        "name" "Leech (HL1)"
        "image" "materials/entities/monster_leech.png"
        "command" "npc_create monster_leech"
    }

    "image_button"
    {
        "name" "Miniturret (HL1)"
        "image" "materials/entities/monster_miniturret.png"
        "command" "npc_create monster_miniturret"
    }

    "image_button"
    {
        "name" "Mortar (HL1)"
        "image" "materials/entities/monster_mortar.png"
        "command" "npc_create monster_mortar"
    }

    "image_button"
    {
        "name" "Nihilanth (HL1)"
        "image" "materials/entities/monster_nihilanth.png"
        "command" "npc_create monster_nihilanth"
    }

    "image_button"
    {
        "name" "Ospery (HL1)"
        "image" "materials/entities/monster_osprey.png"
        "command" "npc_create monster_osprey"
    }

    "image_button"
    {
        "name" "Satchel (HL1)"
        "image" "materials/entities/monster_satchel.png"
        "command" "npc_create monster_satchel"
    }

    "image_button"
    {
        "name" "Scientist (HL1)"
        "image" "materials/entities/monster_scientist.png"
        "command" "npc_create monster_scientist"
    }

    "image_button"
    {
        "name" "Sentry (HL1)"
        "image" "materials/entities/monster_sentry.png"
        "command" "npc_create monster_sentry"
    }

    "image_button"
    {
        "name" "Snark (HL1)"
        "image" "materials/entities/monster_snark.png"
        "command" "npc_create monster_snark"
    }

    "image_button"
    {
        "name" "Tentacle (HL1)"
        "image" "materials/entities/monster_tentacle.png"
        "command" "npc_create monster_tentacle"
    }

    "image_button"
    {
        "name" "Tripmine (HL1)"
        "image" "materials/entities/monster_tripmine.png"
        "command" "npc_create monster_tripmine"
    }

    "image_button"
    {
        "name" "Turret (HL1)"
        "image" "materials/entities/monster_turret.png"
        "command" "npc_create monster_turret"
    }

    "image_button"
    {
        "name" "Zombie (HL1)"
        "image" "materials/entities/monster_zombie.png"
        "command" "npc_create monster_zombie"
    }

}