"Props"
{
	"page_icon"	"materials/icon16/bricks.png"

	"header"
	{
		"text" "All Props"
	}

	"prop"
	{
		"name" "Wood Crate"
		"as_mdlpanel" "1"
		"model" "models/props_junk/wood_crate001a.mdl"
	}

	"prop"
	{
		"name" "Wood Crate 2"
		"as_mdlpanel" "1"
		"model" "models/props_junk/wood_crate002a.mdl"
	}

	"prop"
	{
		"name" "Barrel"
		"as_mdlpanel" "1"
		"model" "models/props_c17/oildrum001.mdl"
	}

	"prop"
	{
		"name" "Explosive Barrel"
		"as_mdlpanel" "1"
		"model" "models/props_c17/oildrum001_explosive.mdl"
	}

	"prop"
	{
		"name" "Blue Barrel"
		"as_mdlpanel" "1"
		"model" "models/props_borealis/bluebarrel001.mdl"
	}

	"prop"
	{
		"name" "Bench"
		"as_mdlpanel" "1"
		"model" "models/props_c17/bench01a.mdl"
	}

	"prop"
	{
		"name" "Bench 2"
		"as_mdlpanel" "1"
		"model" "models/props_trainstation/BenchOutdoor01a.mdl"
	}

	"prop"
	{
		"name" "Bench 3"
		"as_mdlpanel" "1"
		"model" "models/props_trainstation/bench_indoor001a.mdl"
	}

	"prop"
	{
		"name" "Bench 4"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/cafeteria_bench001a.mdl"
	}

	"prop"
	{
		"name" "Chair"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/Furniture_chair01a.mdl"
	}

	"prop"
	{
		"name" "Chair 2"
		"as_mdlpanel" "1"
		"model" "models/props_c17/FurnitureChair001a.mdl"
	}

	"prop"
	{
		"name" "Chair 3"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/Furniture_chair03a.mdl"
	}

	"prop"
	{
		"name" "Chair 4"
		"as_mdlpanel" "1"
		"model" "models/props_c17/chair02a.mdl"
	}

	"prop"
	{
		"name" "Chair 5"
		"as_mdlpanel" "1"
		"model" "models/props_c17/chair_office01a.mdl"
	}

	"prop"
	{
		"name" "Breen Chair"
		"as_mdlpanel" "1"
		"model" "models/props_combine/breenchair.mdl"
	}

	"prop"
	{
		"name" "Armchair"
		"as_mdlpanel" "1"
		"model" "models/props_c17/FurnitureArmchair001a.mdl"
	}

	"prop"
	{
		"name" "Prison Chair"
		"as_mdlpanel" "1"
		"model" "models/props_c17/chair_kleiner03a.mdl"
	}

	"prop"
	{
		"name" "Train Seats"
		"as_mdlpanel" "1"
		"model" "models/props_trainstation/traincar_seats001.mdl"
	}

	"prop"
	{
		"name" "Stool"
		"as_mdlpanel" "1"
		"model" "models/props_c17/chair_stool01a.mdl"
	}

	"prop"
	{
		"name" "Toilet"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/prison_toilet01.mdl"
	}

	"prop"
	{
		"name" "Sink"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/prison_sink001b.mdl"
	}

	"prop"
	{
		"name" "Sink 2"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/SinkKitchen01a.mdl"
	}

	"prop"
	{
		"name" "Radiator"
		"as_mdlpanel" "1"
		"model" "models/props_c17/FurnitureRadiator001a.mdl"
	}

	"prop"
	{
		"name" "Radiator 2"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/Radiator01a.mdl"
	}

	"prop"
	{
		"name" "Bathtub"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/BathTub01a.mdl"
	}

	"prop"
	{
		"name" "Bathtub 2"
		"as_mdlpanel" "1"
		"model" "models/props_c17/FurnitureBathtub001a.mdl"
	}

	"prop"
	{
		"name" "Fridge"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/kitchen_fridge001a.mdl"
	}

	"prop"
	{
		"name" "Fridge 2"
		"as_mdlpanel" "1"
		"model" "models/props_c17/FurnitureFridge001a.mdl"
	}

	"prop"
	{
		"name" "Fridge 3"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/refrigerator01a.mdl"
	}

	"prop"
	{
		"name" "Fridge Door"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/refrigeratorDoor01a.mdl"
	}

	"prop"
	{
		"name" "Fridge Door 2"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/refrigeratorDoor02a.mdl"
	}

	"prop"
	{
		"name" "Shelf 1"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/kitchen_shelf001a.mdl"
	}

	"prop"
	{
		"name" "Shelf 2"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/kitchen_shelf002a.mdl"
	}

	"prop"
	{
		"name" "Cabinet Drawer"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/Furniture_CabinetDrawer01a.mdl"
	}

	"prop"
	{
		"name" "Cabinet Drawer 2"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/Furniture_CabinetDrawer02a.mdl"
	}

	"prop"
	{
		"name" "Lockers"
		"as_mdlpanel" "1"
		"model" "models/props_lab/lockers.mdl"
	}

	"prop"
	{
		"name" "Locker Door"
		"as_mdlpanel" "1"
		"model" "models/props_lab/lockerdoorleft.mdl"
	}

	"prop"
	{
		"name" "Counter"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/kitchen_counter001a.mdl"
	}

	"prop"
	{
		"name" "Counter 2"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/kitchen_counter001b.mdl"
	}

	"prop"
	{
		"name" "Counter 3"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/kitchen_counter001c.mdl"
	}

	"prop"
	{
		"name" "Counter 4"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/kitchen_counter001d.mdl"
	}

	"prop"
	{
		"name" "Stove"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/kitchen_stove001a.mdl"
	}

	"prop"
	{
		"name" "Stove 2"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/kitchen_stove002a.mdl"
	}

	"prop"
	{
		"name" "Table"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/cafeteria_table001a.mdl"
	}

	"prop"
	{
		"name" "Table 2"
		"as_mdlpanel" "1"
		"model" "models/props_c17/FurnitureTable001a.mdl"
	}

	"prop"
	{
		"name" "Table 3"
		"as_mdlpanel" "1"
		"model" "models/props_c17/FurnitureTable002a.mdl"
	}

	"prop"
	{
		"name" "Table 4"
		"as_mdlpanel" "1"
		"model" "models/props_c17/FurnitureTable003a.mdl"
	}

	"prop"
	{
		"name" "Drawer"
		"as_mdlpanel" "1"
		"model" "models/props_c17/FurnitureDrawer001a.mdl"
	}

	"prop"
	{
		"name" "Drawer 2"
		"as_mdlpanel" "1"
		"model" "models/props_c17/FurnitureDrawer002a.mdl"
	}

	"prop"
	{
		"name" "Drawer 3"
		"as_mdlpanel" "1"
		"model" "models/props_c17/FurnitureDrawer003a.mdl"
	}

	"prop"
	{
		"name" "Bed"
		"as_mdlpanel" "1"
		"model" "models/props_c17/FurnitureBed001a.mdl"
	}

	"prop"
	{
		"name" "Mattres"
		"as_mdlpanel" "1"
		"model" "models/props_c17/FurnitureMattress001a.mdl"
	}

	"prop"
	{
		"name" "Desk"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/Furniture_Desk01a.mdl"
	}

	"prop"
	{
		"name" "File Cabinet"
		"as_mdlpanel" "1"
		"model" "models/props_lab/filecabinet02.mdl"
	}

	"prop"
	{
		"name" "Small Lamp"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/Furniture_Lamp01a.mdl"
	}

	"prop"
	{
		"name" "Shelf 3"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/Furniture_shelf01a.mdl"
	}

	"prop"
	{
		"name" "Vanity"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/Furniture_Vanity01a.mdl"
	}

	"prop"
	{
		"name" "Cupboard"
		"as_mdlpanel" "1"
		"model" "models/props_c17/FurnitureCupboard001a.mdl"
	}

	"prop"
	{
		"name" "Dresser"
		"as_mdlpanel" "1"
		"model" "models/props_c17/FurnitureDresser001a.mdl"
	}

	"prop"
	{
		"name" "Fireplace"
		"as_mdlpanel" "1"
		"model" "models/props_c17/FurnitureFireplace001a.mdl"
	}

	"prop"
	{
		"name" "Trashcan"
		"as_mdlpanel" "1"
		"model" "models/props_trainstation/trashcan_indoor001a.mdl"
	}

	"prop"
	{
		"name" "Trashcan 2"
		"as_mdlpanel" "1"
		"model" "models/props_trainstation/trashcan_indoor001b.mdl"
	}

	"prop"
	{
		"name" "Couch"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/Furniture_Couch01a.mdl"
	}

	"prop"
	{
		"name" "Couch 2"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/Furniture_Couch02a.mdl"
	}

	"prop"
	{
		"name" "Couch 3"
		"as_mdlpanel" "1"
		"model" "models/props_c17/FurnitureCouch001a.mdl"
	}

	"prop"
	{
		"name" "Couch 4"
		"as_mdlpanel" "1"
		"model" "models/props_c17/FurnitureCouch002a.mdl"
	}

	"prop"
	{
		"name" "Wooden Pallet"
		"as_mdlpanel" "1"
		"model" "models/props_junk/wood_pallet001a.mdl"
	}

	"prop"
	{
		"name" "Metal Desk"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/controlroom_desk001a.mdl"
	}

	"prop"
	{
		"name" "Breen Desk"
		"as_mdlpanel" "1"
		"model" "models/props_combine/breendesk.mdl"
	}

	"prop"
	{
		"name" "Dumpster"
		"as_mdlpanel" "1"
		"model" "models/props_junk/TrashDumpster02.mdl"
	}

	"prop"
	{
		"name" "Dumpster Lid"
		"as_mdlpanel" "1"
		"model" "models/props_junk/TrashDumpster02b.mdl"
	}

	"prop"
	{
		"name" "Plank"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/dockplank01b.mdl"
	}

	"prop"
	{
		"name" "Ravenholm Sign"
		"as_mdlpanel" "1"
		"model" "models/props_junk/ravenholmsign.mdl"
	}

	"prop"
	{
		"name" "Vending Machine"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/VendingMachineSoda01a.mdl"
	}

	"prop"
	{
		"name" "Vending Door"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/VendingMachineSoda01a_door.mdl"
	}

	"prop"
	{
		"name" "Ladder"
		"as_mdlpanel" "1"
		"model" "models/props_c17/metalladder001.mdl"
	}

	"prop"
	{
		"name" "Ladder 2"
		"as_mdlpanel" "1"
		"model" "models/props_c17/metalladder002.mdl"
	}

	"prop"
	{
		"name" "Ladder 3"
		"as_mdlpanel" "1"
		"model" "models/props_c17/metalladder002b.mdl"
	}

	"prop"
	{
		"name" "Ladder 4"
		"as_mdlpanel" "1"
		"model" "models/props_c17/metalladder003.mdl"
	}

	"prop"
	{
		"name" "Slide"
		"as_mdlpanel" "1"
		"model" "models/props_c17/playgroundslide01.mdl"
	}

	"prop"
	{
		"name" "TickTac"
		"as_mdlpanel" "1"
		"model" "models/props_c17/playgroundTick-tack-toe_block01a.mdl"
	}

	"prop"
	{
		"name" "TickTac Post"
		"as_mdlpanel" "1"
		"model" "models/props_c17/playgroundTick-tack-toe_post01.mdl"
	}

	"prop"
	{
		"name" "Carousel"
		"as_mdlpanel" "1"
		"model" "models/props_c17/playground_carousel01.mdl"
	}

	"prop"
	{
		"name" "Jungle Gym"
		"as_mdlpanel" "1"
		"model" "models/props_c17/playground_jungle_gym01a.mdl"
	}

	"prop"
	{
		"name" "Jungle Gym 2"
		"as_mdlpanel" "1"
		"model" "models/props_c17/playground_jungle_gym01b.mdl"
	}

	"prop"
	{
		"name" "Trash Bin"
		"as_mdlpanel" "1"
		"model" "models/props_junk/TrashBin01a.mdl"
	}

	"prop"
	{
		"name" "Push Cart"
		"as_mdlpanel" "1"
		"model" "models/props_junk/PushCart01a.mdl"
	}

	"prop"
	{
		"name" "Buoy"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/buoy01.mdl"
	}

	"prop"
	{
		"name" "Harpoon"
		"as_mdlpanel" "1"
		"model" "models/props_junk/harpoon002a.mdl"
	}

	"prop"
	{
		"name" "Wood Board"
		"as_mdlpanel" "1"
		"model" "models/props_debris/wood_board01a.mdl"
	}

	"prop"
	{
		"name" "Wood Board 2"
		"as_mdlpanel" "1"
		"model" "models/props_debris/wood_board02a.mdl"
	}

	"prop"
	{
		"name" "Wood Board 3"
		"as_mdlpanel" "1"
		"model" "models/props_debris/wood_board03a.mdl"
	}

	"prop"
	{
		"name" "Wood Board 4"
		"as_mdlpanel" "1"
		"model" "models/props_debris/wood_board04a.mdl"
	}

	"prop"
	{
		"name" "Wood Board 5"
		"as_mdlpanel" "1"
		"model" "models/props_debris/wood_board05a.mdl"
	}

	"prop"
	{
		"name" "Wood Board 6"
		"as_mdlpanel" "1"
		"model" "models/props_debris/wood_board06a.mdl"
	}

	"prop"
	{
		"name" "Wood Board 7"
		"as_mdlpanel" "1"
		"model" "models/props_debris/wood_board07a.mdl"
	}

	"prop"
	{
		"name" "Barrier"
		"as_mdlpanel" "1"
		"model" "models/props_c17/concrete_barrier001a.mdl"
	}

	"prop"
	{
		"name" "Barricade"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/barricade001a.mdl"
	}

	"prop"
	{
		"name" "Barricade 2"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/barricade002a.mdl"
	}

	"prop"
	{
		"name" "Gas Pump"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/gaspump001a.mdl"
	}

	"prop"
	{
		"name" "Dock Pole"
		"as_mdlpanel" "1"
		"model" "models/props_docks/dock01_pole01a_128.mdl"
	}

	"prop"
	{
		"name" "Dock Pole Long"
		"as_mdlpanel" "1"
		"model" "models/props_docks/dock01_pole01a_256.mdl"
	}

	"prop"
	{
		"name" "Door"
		"as_mdlpanel" "1"
		"model" "models/props_c17/door01_left.mdl"
	}

	"prop"
	{
		"name" "Glass Door"
		"as_mdlpanel" "1"
		"model" "models/props_c17/door02_double.mdl"
	}

	"prop"
	{
		"name" "Ship Door"
		"as_mdlpanel" "1"
		"model" "models/props_borealis/borealis_door001a.mdl"
	}

	"prop"
	{
		"name" "Blast Door"
		"as_mdlpanel" "1"
		"model" "models/props_lab/blastdoor001a.mdl"
	}

	"prop"
	{
		"name" "Blast Door 2"
		"as_mdlpanel" "1"
		"model" "models/props_lab/blastdoor001b.mdl"
	}

	"prop"
	{
		"name" "Blast Door 3"
		"as_mdlpanel" "1"
		"model" "models/props_lab/blastdoor001c.mdl"
	}

	"prop"
	{
		"name" "Wood Fence"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/wood_fence01a.mdl"
	}

	"prop"
	{
		"name" "Wood Fence 2"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/wood_fence02a.mdl"
	}

	"prop"
	{
		"name" "Metal Panel"
		"as_mdlpanel" "1"
		"model" "models/props_debris/metal_panel01a.mdl"
	}

	"prop"
	{
		"name" "Metal Panel 2"
		"as_mdlpanel" "1"
		"model" "models/props_debris/metal_panel02a.mdl"
	}

	"prop"
	{
		"name" "Cargo Container"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/cargo_container01.mdl"
	}

	"prop"
	{
		"name" "Cargo Container 2"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/cargo_container01b.mdl"
	}

	"prop"
	{
		"name" "Kennel"
		"as_mdlpanel" "1"
		"model" "models/props_lab/kennel.mdl"
	}

	"prop"
	{
		"name" "Orange Tube"
		"as_mdlpanel" "1"
		"model" "models/props_lab/generatortube.mdl"
	}

	"prop"
	{
		"name" "Sign Pole"
		"as_mdlpanel" "1"
		"model" "models/props_c17/signpole001.mdl"
	}

	"prop"
	{
		"name" "Iron Beam"
		"as_mdlpanel" "1"
		"model" "models/props_junk/iBeam01a.mdl"
	}

	"prop"
	{
		"name" "Iron Beam 2"
		"as_mdlpanel" "1"
		"model" "models/props_junk/iBeam01a_cluster01.mdl"
	}

	"prop"
	{
		"name" "Doll"
		"as_mdlpanel" "1"
		"model" "models/props_c17/doll01.mdl"
	}

	"prop"
	{
		"name" "Clock"
		"as_mdlpanel" "1"
		"model" "models/props_c17/clock01.mdl"
	}

	"prop"
	{
		"name" "Cash Reg"
		"as_mdlpanel" "1"
		"model" "models/props_c17/cashregister01a.mdl"
	}

	"prop"
	{
		"name" "Chopper Bomb"
		"as_mdlpanel" "1"
		"model" "models/Combine_Helicopter/helicopter_bomb01.mdl"
	}

	"prop"
	{
		"name" "Tram Lever"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/tram_lever01.mdl"
	}

	"prop"
	{
		"name" "Tram Lever Base"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/tram_leverbase01.mdl"
	}

	"prop"
	{
		"name" "Wrench"
		"as_mdlpanel" "1"
		"model" "models/props_c17/tools_wrench01a.mdl"
	}

	"prop"
	{
		"name" "Pliers"
		"as_mdlpanel" "1"
		"model" "models/props_c17/tools_pliers01a.mdl"
	}

	"prop"
	{
		"name" "Meat Grinder"
		"as_mdlpanel" "1"
		"model" "models/props_c17/grinderclamp01a.mdl"
	}

	"prop"
	{
		"name" "Door Slotted"
		"as_mdlpanel" "1"
		"model" "models/props_doors/door03_slotted_left.mdl"
	}

	"prop"
	{
		"name" "Weapon Stripper"
		"as_mdlpanel" "1"
		"model" "models/props_combine/weaponstripper.mdl"
	}

	"prop"
	{
		"name" "Streetsign"
		"as_mdlpanel" "1"
		"model" "models/props_c17/streetsign001c.mdl"
	}

	"prop"
	{
		"name" "Streetsign 2"
		"as_mdlpanel" "1"
		"model" "models/props_c17/streetsign002b.mdl"
	}

	"prop"
	{
		"name" "Streetsign 3"
		"as_mdlpanel" "1"
		"model" "models/props_c17/streetsign003b.mdl"
	}

	"prop"
	{
		"name" "Streetsign 4"
		"as_mdlpanel" "1"
		"model" "models/props_c17/streetsign004e.mdl"
	}

	"prop"
	{
		"name" "Streetsign 5"
		"as_mdlpanel" "1"
		"model" "models/props_c17/streetsign004f.mdl"
	}

	"prop"
	{
		"name" "Streetsign 6"
		"as_mdlpanel" "1"
		"model" "models/props_c17/streetsign005b.mdl"
	}

	"prop"
	{
		"name" "Streetsign 7"
		"as_mdlpanel" "1"
		"model" "models/props_c17/streetsign005c.mdl"
	}

	"prop"
	{
		"name" "Streetsign 8"
		"as_mdlpanel" "1"
		"model" "models/props_c17/streetsign005d.mdl"
	}

	"prop"
	{
		"name" "Matt Pipe"
		"as_mdlpanel" "1"
		"model" "models/props_canal/mattpipe.mdl"
	}

	"prop"
	{
		"name" "Pot"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/pot01a.mdl"
	}

	"prop"
	{
		"name" "Pot 2"
		"as_mdlpanel" "1"
		"model" "models/props_interiors/pot02a.mdl"
	}

	"prop"
	{
		"name" "Concrete Block"
		"as_mdlpanel" "1"
		"model" "models/props_debris/concrete_cynderblock001.mdl"
	}

	"prop"
	{
		"name" "Cinder Block"
		"as_mdlpanel" "1"
		"model" "models/props_junk/CinderBlock01a.mdl"
	}

	"prop"
	{
		"name" "Breen Bust"
		"as_mdlpanel" "1"
		"model" "models/props_combine/breenbust.mdl"
	}

	"prop"
	{
		"name" "Combine Light"
		"as_mdlpanel" "1"
		"model" "models/props_combine/breenlight.mdl"
	}

	"prop"
	{
		"name" "Meat Hook"
		"as_mdlpanel" "1"
		"model" "models/props_junk/meathook001a.mdl"
	}

	"prop"
	{
		"name" "Suit Charger"
		"as_mdlpanel" "1"
		"model" "models/props_combine/suit_charger001.mdl"
	}

	"prop"
	{
		"name" "Bucket"
		"as_mdlpanel" "1"
		"model" "models/props_junk/MetalBucket01a.mdl"
	}

	"prop"
	{
		"name" "Bucket 2"
		"as_mdlpanel" "1"
		"model" "models/props_junk/MetalBucket02a.mdl"
	}

	"prop"
	{
		"name" "Saw blade"
		"as_mdlpanel" "1"
		"model" "models/props_junk/sawblade001a.mdl"
	}

	"prop"
	{
		"name" "Magnifying Lamp"
		"as_mdlpanel" "1"
		"model" "models/props_c17/light_magnifyinglamp02.mdl"
	}

	"prop"
	{
		"name" "Plant Pot"
		"as_mdlpanel" "1"
		"model" "models/props_junk/terracotta01.mdl"
	}

	"prop"
	{
		"name" "Rock"
		"as_mdlpanel" "1"
		"model" "models/props_junk/Rock001a.mdl"
	}

	"prop"
	{
		"name" "Watermelon"
		"as_mdlpanel" "1"
		"model" "models/props_junk/watermelon01.mdl"
	}

	"prop"
	{
		"name" "Dog Sign"
		"as_mdlpanel" "1"
		"model" "models/props_lab/bewaredog.mdl"
	}

	"prop"
	{
		"name" "Traffic Cone"
		"as_mdlpanel" "1"
		"model" "models/props_junk/TrafficCone001a.mdl"
	}

	"prop"
	{
		"name" "Cremator Head"
		"as_mdlpanel" "1"
		"model" "models/props_lab/crematorcase.mdl"
	}

	"prop"
	{
		"name" "Jar"
		"as_mdlpanel" "1"
		"model" "models/props_lab/jar01a.mdl"
	}

	"prop"
	{
		"name" "Jar 2"
		"as_mdlpanel" "1"
		"model" "models/props_lab/jar01b.mdl"
	}

	"prop"
	{
		"name" "Hev Plate"
		"as_mdlpanel" "1"
		"model" "models/props_lab/hevplate.mdl"
	}

	"prop"
	{
		"name" "Keypad"
		"as_mdlpanel" "1"
		"model" "models/props_lab/keypad.mdl"
	}

	"prop"
	{
		"name" "Radio"
		"as_mdlpanel" "1"
		"model" "models/props_lab/citizenradio.mdl"
	}

	"prop"
	{
		"name" "TV"
		"as_mdlpanel" "1"
		"model" "models/props_c17/tv_monitor01.mdl"
	}

	"prop"
	{
		"name" "Monitor"
		"as_mdlpanel" "1"
		"model" "models/props_lab/monitor01a.mdl"
	}

	"prop"
	{
		"name" "Monitor 2"
		"as_mdlpanel" "1"
		"model" "models/props_lab/monitor01b.mdl"
	}

	"prop"
	{
		"name" "Monitor 3"
		"as_mdlpanel" "1"
		"model" "models/props_lab/monitor02.mdl"
	}

	"prop"
	{
		"name" "Lab Receiver"
		"as_mdlpanel" "1"
		"model" "models/props_lab/reciever01a.mdl"
	}

	"prop"
	{
		"name" "Lab Receiver 2"
		"as_mdlpanel" "1"
		"model" "models/props_lab/reciever01b.mdl"
	}

	"prop"
	{
		"name" "Lab Receiver 3"
		"as_mdlpanel" "1"
		"model" "models/props_lab/reciever01c.mdl"
	}

	"prop"
	{
		"name" "Lab Receiver 4"
		"as_mdlpanel" "1"
		"model" "models/props_lab/reciever01d.mdl"
	}

	"prop"
	{
		"name" "Keyboard"
		"as_mdlpanel" "1"
		"model" "models/props_c17/computer01_keyboard.mdl"
	}

	"prop"
	{
		"name" "Hard Drive"
		"as_mdlpanel" "1"
		"model" "models/props_lab/harddrive01.mdl"
	}

	"prop"
	{
		"name" "Hard Drive 2"
		"as_mdlpanel" "1"
		"model" "models/props_lab/harddrive02.mdl"
	}

	"prop"
	{
		"name" "Console"
		"as_mdlpanel" "1"
		"model" "models/props_c17/consolebox01a.mdl"
	}

	"prop"
	{
		"name" "Console 2"
		"as_mdlpanel" "1"
		"model" "models/props_c17/consolebox03a.mdl"
	}

	"prop"
	{
		"name" "Console 3"
		"as_mdlpanel" "1"
		"model" "models/props_c17/consolebox05a.mdl"
	}

	"prop"
	{
		"name" "Phone Reciever"
		"as_mdlpanel" "1"
		"model" "models/props_trainstation/payphone_reciever001a.mdl"
	}

	"prop"
	{
		"name" "Hula Doll"
		"as_mdlpanel" "1"
		"model" "models/props_lab/huladoll.mdl"
	}

	"prop"
	{
		"name" "Desk Lamp"
		"as_mdlpanel" "1"
		"model" "models/props_lab/desklamp01.mdl"
	}

	"prop"
	{
		"name" "Cactus"
		"as_mdlpanel" "1"
		"model" "models/props_lab/cactus.mdl"
	}

	"prop"
	{
		"name" "Clipboard"
		"as_mdlpanel" "1"
		"model" "models/props_lab/clipboard.mdl"
	}

	"prop"
	{
		"name" "Photo"
		"as_mdlpanel" "1"
		"model" "models/props_lab/frame002a.mdl"
	}

	"prop"
	{
		"name" "Clock 2"
		"as_mdlpanel" "1"
		"model" "models/props_combine/breenclock.mdl"
	}

	"prop"
	{
		"name" "Globe"
		"as_mdlpanel" "1"
		"model" "models/props_combine/breenglobe.mdl"
	}

	"prop"
	{
		"name" "Rock 2"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/rockcliff01b.mdl"
	}

	"prop"
	{
		"name" "Rock 3"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/rockcliff01c.mdl"
	}

	"prop"
	{
		"name" "Rock 4"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/rockcliff01e.mdl"
	}

	"prop"
	{
		"name" "Big Rock"
		"as_mdlpanel" "1"
		"model" "models/props_lab/BigRock.mdl"
	}

	"prop"
	{
		"name" "Crab Cannister"
		"as_mdlpanel" "1"
		"model" "models/props_combine/headcrabcannister01a.mdl"
	}

	"prop"
	{
		"name" "Crab Cannister 2"
		"as_mdlpanel" "1"
		"model" "models/props_combine/headcrabcannister01b.mdl"
	}

	"prop"
	{
		"name" "Tram Bracket"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/tram_bracket01.mdl"
	}

	"prop"
	{
		"name" "Speaker Clust"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/SpeakerCluster01a.mdl"
	}

	"prop"
	{
		"name" "Chimney"
		"as_mdlpanel" "1"
		"model" "models/props_animated_breakable/Smokestack.mdl"
	}

	"prop"
	{
		"name" "Cannister"
		"as_mdlpanel" "1"
		"model" "models/props_c17/canister01a.mdl"
	}

	"prop"
	{
		"name" "Cannister 2"
		"as_mdlpanel" "1"
		"model" "models/props_c17/canister02a.mdl"
	}

	"prop"
	{
		"name" "Propane Cannister"
		"as_mdlpanel" "1"
		"model" "models/props_junk/PropaneCanister001a.mdl"
	}

	"prop"
	{
		"name" "Propane Tank"
		"as_mdlpanel" "1"
		"model" "models/props_junk/propane_tank001a.mdl"
	}

	"prop"
	{
		"name" "Propane"
		"as_mdlpanel" "1"
		"model" "models/props_c17/canister_propane01a.mdl"
	}

	"prop"
	{
		"name" "Bicycle"
		"as_mdlpanel" "1"
		"model" "models/props_junk/bicycle01a.mdl"
	}

	"prop"
	{
		"name" "Carboard"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage_carboard001a.mdl"
	}

	"prop"
	{
		"name" "Carboard 2"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage_carboard002a.mdl"
	}

	"prop"
	{
		"name" "Carboard Box"
		"as_mdlpanel" "1"
		"model" "models/props_junk/cardboard_box001b.mdl"
	}

	"prop"
	{
		"name" "Carboard Box 2"
		"as_mdlpanel" "1"
		"model" "models/props_junk/cardboard_box002a.mdl"
	}

	"prop"
	{
		"name" "Carboard Box 3"
		"as_mdlpanel" "1"
		"model" "models/props_junk/cardboard_box002b.mdl"
	}

	"prop"
	{
		"name" "Carboard Box 4"
		"as_mdlpanel" "1"
		"model" "models/props_junk/cardboard_box003a.mdl"
	}

	"prop"
	{
		"name" "Carboard Box 5"
		"as_mdlpanel" "1"
		"model" "models/props_junk/cardboard_box003b.mdl"
	}

	"prop"
	{
		"name" "Garbage"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage128_composite001a.mdl"
	}

	"prop"
	{
		"name" "Garbage 2"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage128_composite001b.mdl"
	}

	"prop"
	{
		"name" "Garbage 3"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage128_composite001c.mdl"
	}

	"prop"
	{
		"name" "Garbage 4"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage128_composite001d.mdl"
	}

	"prop"
	{
		"name" "Garbage 5"
		"as_mdlpanel" "1"
		"model" "models/props_junk/TrashCluster01a.mdl"
	}

	"prop"
	{
		"name" "Gear"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/gear01.mdl"
	}

	"prop"
	{
		"name" "Cooling Tank"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/horizontalcoolingtank04.mdl"
	}

	"prop"
	{
		"name" "Vent"
		"as_mdlpanel" "1"
		"model" "models/props_junk/vent001.mdl"
	}

	"prop"
	{
		"name" "Display Cooler"
		"as_mdlpanel" "1"
		"model" "models/props_c17/display_cooler01a.mdl"
	}

	"prop"
	{
		"name" "Fountain"
		"as_mdlpanel" "1"
		"model" "models/props_c17/fountain_01.mdl"
	}

	"prop"
	{
		"name" "Glass Bottle"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage_glassbottle001a.mdl"
	}

	"prop"
	{
		"name" "Glass Bottle 2"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage_glassbottle002a.mdl"
	}

	"prop"
	{
		"name" "Glass Bottle 3"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage_glassbottle003a.mdl"
	}

	"prop"
	{
		"name" "Glass Bottle 4"
		"as_mdlpanel" "1"
		"model" "models/props_junk/GlassBottle01a.mdl"
	}

	"prop"
	{
		"name" "Plastic Bottle"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage_plasticbottle001a.mdl"
	}

	"prop"
	{
		"name" "Plastic Bottle 2"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage_plasticbottle002a.mdl"
	}

	"prop"
	{
		"name" "Plastic Bottle 3"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage_plasticbottle003a.mdl"
	}

	"prop"
	{
		"name" "Newspaper"
		"as_mdlpanel" "1"
		"model" "models/props_c17/paper01.mdl"
	}

	"prop"
	{
		"name" "Newspaper 2"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage_newspaper001a.mdl"
	}

	"prop"
	{
		"name" "Plastic Bucket"
		"as_mdlpanel" "1"
		"model" "models/props_junk/plasticbucket001a.mdl"
	}

	"prop"
	{
		"name" "Plastic Crate"
		"as_mdlpanel" "1"
		"model" "models/props_junk/PlasticCrate01a.mdl"
	}

	"prop"
	{
		"name" "Can"
		"as_mdlpanel" "1"
		"model" "models/props_junk/PopCan01a.mdl"
	}

	"prop"
	{
		"name" "Metal Can"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage_metalcan001a.mdl"
	}

	"prop"
	{
		"name" "Metal Can 2"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage_metalcan002a.mdl"
	}

	"prop"
	{
		"name" "Take Out"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage_takeoutcarton001a.mdl"
	}

	"prop"
	{
		"name" "Bag"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage_bag001a.mdl"
	}

	"prop"
	{
		"name" "Coffee Mug"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage_coffeemug001a.mdl"
	}

	"prop"
	{
		"name" "Milk Carton"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage_milkcarton001a.mdl"
	}

	"prop"
	{
		"name" "Milk Carton 2"
		"as_mdlpanel" "1"
		"model" "models/props_junk/garbage_milkcarton002a.mdl"
	}

	"prop"
	{
		"name" "Glass Jug"
		"as_mdlpanel" "1"
		"model" "models/props_junk/glassjug01.mdl"
	}

	"prop"
	{
		"name" "Shoe"
		"as_mdlpanel" "1"
		"model" "models/props_junk/Shoe001a.mdl"
	}

	"prop"
	{
		"name" "Shovel"
		"as_mdlpanel" "1"
		"model" "models/props_junk/Shovel01a.mdl"
	}

	"prop"
	{
		"name" "Paintcan"
		"as_mdlpanel" "1"
		"model" "models/props_junk/metal_paintcan001a.mdl"
	}

	"prop"
	{
		"name" "Paintcan 2"
		"as_mdlpanel" "1"
		"model" "models/props_junk/metal_paintcan001b.mdl"
	}

	"prop"
	{
		"name" "Gascan"
		"as_mdlpanel" "1"
		"model" "models/props_junk/gascan001a.mdl"
	}

	"prop"
	{
		"name" "Metal Gascan"
		"as_mdlpanel" "1"
		"model" "models/props_junk/metalgascan.mdl"
	}

	"prop"
	{
		"name" "Teleporter"
		"as_mdlpanel" "1"
		"model" "models/props_lab/teleplatform.mdl"
	}

	"prop"
	{
		"name" "Payphone"
		"as_mdlpanel" "1"
		"model" "models/props_trainstation/payphone001a.mdl"
	}

	"prop"
	{
		"name" "Pole"
		"as_mdlpanel" "1"
		"model" "models/props_trainstation/pole_448Connection002b.mdl"
	}

	"prop"
	{
		"name" "Handrail"
		"as_mdlpanel" "1"
		"model" "models/props_trainstation/payphone001a.mdl"
	}

	"prop"
	{
		"name" "Plug"
		"as_mdlpanel" "1"
		"model" "models/props_lab/tpplug.mdl"
	}

	"prop"
	{
		"name" "Plug Holder"
		"as_mdlpanel" "1"
		"model" "models/props_lab/tpplugholder_single.mdl"
	}

	"prop"
	{
		"name" "Train Post"
		"as_mdlpanel" "1"
		"model" "models/props_trainstation/trainstation_post001.mdl"
	}

	"prop"
	{
		"name" "Horse"
		"as_mdlpanel" "1"
		"model" "models/props_c17/statue_horse.mdl"
	}

	"prop"
	{
		"name" "Propeller Blade"
		"as_mdlpanel" "1"
		"model" "models/props_c17/TrapPropeller_Blade.mdl"
	}

	"prop"
	{
		"name" "Propeller Engine"
		"as_mdlpanel" "1"
		"model" "models/props_c17/TrapPropeller_Engine.mdl"
	}

	"prop"
	{
		"name" "Propeller Lever"
		"as_mdlpanel" "1"
		"model" "models/props_c17/TrapPropeller_Lever.mdl"
	}

	"prop"
	{
		"name" "Tree Poplar"
		"as_mdlpanel" "1"
		"model" "models/props_foliage/tree_poplar_01.mdl"
	}

	"prop"
	{
		"name" "Oak Tree"
		"as_mdlpanel" "1"
		"model" "models/props_foliage/oak_tree01.mdl"
	}

	"prop"
	{
		"name" "Cliff Tree"
		"as_mdlpanel" "1"
		"model" "models/props_foliage/tree_cliff_01a.mdl"
	}

	"prop"
	{
		"name" "Tree Deciduous"
		"as_mdlpanel" "1"
		"model" "models/props_foliage/tree_deciduous_01a.mdl"
	}

	"prop"
	{
		"name" "Tree Deciduous 2"
		"as_mdlpanel" "1"
		"model" "models/props_foliage/tree_deciduous_02a.mdl"
	}

	"prop"
	{
		"name" "Tree Deciduous 3"
		"as_mdlpanel" "1"
		"model" "models/props_foliage/tree_deciduous_03a.mdl"
	}

	"prop"
	{
		"name" "Tree Deciduous 4"
		"as_mdlpanel" "1"
		"model" "models/props_foliage/tree_deciduous_03b.mdl"
	}

	"prop"
	{
		"name" "Car"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/car002a.mdl"
	}

	"prop"
	{
		"name" "Car 2"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/car002b.mdl"
	}

	"prop"
	{
		"name" "Car 2"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/car003a.mdl"
	}

	"prop"
	{
		"name" "Car 3"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/car003b.mdl"
	}

	"prop"
	{
		"name" "Car 4"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/car004a.mdl"
	}

	"prop"
	{
		"name" "Car 5"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/car004b.mdl"
	}

	"prop"
	{
		"name" "Car6"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/car005a.mdl"
	}

	"prop"
	{
		"name" "Car 7"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/car005b.mdl"
	}

	"prop"
	{
		"name" "Car 8"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/car001a_hatchback.mdl"
	}

	"prop"
	{
		"name" "Car 9"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/car001b_hatchback.mdl"
	}

	"prop"
	{
		"name" "Truck"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/truck001a.mdl"
	}

	"prop"
	{
		"name" "Truck 2"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/truck002a_cab.mdl"
	}

	"prop"
	{
		"name" "Truck 3"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/truck003a.mdl"
	}

	"prop"
	{
		"name" "Van"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/van001a.mdl"
	}

	"prop"
	{
		"name" "Wagon"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/wagon001a.mdl"
	}

	"prop"
	{
		"name" "Combine APC"
		"as_mdlpanel" "1"
		"model" "models/combine_apc_wheelcollision.mdl"
	}

	"prop"
	{
		"name" "Car (Ragdoll)"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/car001a_phy.mdl"
	}

	"prop"
	{
		"name" "Conscript APC"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/apc001.mdl"
	}

	"prop"
	{
		"name" "Boat"
		"as_mdlpanel" "1"
		"model" "models/props_wasteland/boat_01.mdl"
	}

	"prop"
	{
		"name" "Boat 2"
		"as_mdlpanel" "1"
		"model" "models/props_canal/boat001a.mdl"
	}

	"prop"
	{
		"name" "Boat 3"
		"as_mdlpanel" "1"
		"model" "models/props_canal/boat001b.mdl"
	}

	"prop"
	{
		"name" "Boat 4"
		"as_mdlpanel" "1"
		"model" "models/props_canal/boat002b.mdl"
	}

	"prop"
	{
		"name" "Generator"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/generatortrailer01.mdl"
	}

	"prop"
	{
		"name" "Trailer"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/trailer001a.mdl"
	}

	"prop"
	{
		"name" "Trailer 2"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/trailer002a.mdl"
	}

	"prop"
	{
		"name" "Wheel Barrow"
		"as_mdlpanel" "1"
		"model" "models/props_junk/Wheebarrow01a.mdl"
	}

	"prop"
	{
		"name" "Train"
		"as_mdlpanel" "1"
		"model" "models/props_trainstation/train001.mdl"
	}

	"prop"
	{
		"name" "Train 2"
		"as_mdlpanel" "1"
		"model" "models/props_trainstation/train003.mdl"
	}

	"prop"
	{
		"name" "Combine Train"
		"as_mdlpanel" "1"
		"model" "models/props_combine/combine_train02a.mdl"
	}

	"prop"
	{
		"name" "Combine Train 2"
		"as_mdlpanel" "1"
		"model" "models/props_combine/combine_train02b.mdl"
	}

	"prop"
	{
		"name" "Car Wheel"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/carparts_wheel01a.mdl"
	}

	"prop"
	{
		"name" "APC Wheel"
		"as_mdlpanel" "1"
		"model" "models/props_vehicles/apc_tire001.mdl"
	}

	"prop"
	{
		"name" "Crowbar"
		"as_mdlpanel" "1"
		"model" "models/weapons/w_crowbar.mdl"
	}

	"prop"
	{
		"name" "Pistol"
		"as_mdlpanel" "1"
		"model" "models/weapons/w_pistol.mdl"
	}

	"prop"
	{
		"name" "357"
		"as_mdlpanel" "1"
		"model" "models/weapons/w_357.mdl"
	}

	"prop"
	{
		"name" "Crossbow"
		"as_mdlpanel" "1"
		"model" "models/weapons/w_crossbow.mdl"
	}

	"prop"
	{
		"name" "Smg1"
		"as_mdlpanel" "1"
		"model" "models/weapons/w_smg1.mdl"
	}

	"prop"
	{
		"name" "Ar2"
		"as_mdlpanel" "1"
		"model" "models/weapons/w_irifle.mdl"
	}

	"prop"
	{
		"name" "Shotgun"
		"as_mdlpanel" "1"
		"model" "models/Weapons/w_shotgun.mdl"
	}

	"prop"
	{
		"name" "Frag Grenade"
		"as_mdlpanel" "1"
		"model" "models/weapons/w_grenade.mdl"
	}

	"prop"
	{
		"name" "RPG"
		"as_mdlpanel" "1"
		"model" "models/weapons/w_rocket_launcher.mdl"
	}

	"prop"
	{
		"name" "Bugbait"
		"as_mdlpanel" "1"
		"model" "models/weapons/w_bugbait.mdl"
	}

	"prop"
	{
		"name" "Gravity Gun"
		"as_mdlpanel" "1"
		"model" "models/weapons/w_physics.mdl"
	}

	"prop"
	{
		"name" "Stunstick"
		"as_mdlpanel" "1"
		"model" "models/weapons/w_stunbaton.mdl"
	}

	"prop"
	{
		"name" "Alyx Gun"
		"as_mdlpanel" "1"
		"model" "models/weapons/w_alyx_gun.mdl"
	}

	"prop"
	{
		"name" "Annabelle"
		"as_mdlpanel" "1"
		"model" "models/weapons/w_annabelle.mdl"
	}

	"prop"
	{
		"name" "Supplies Smg1"
		"as_mdlpanel" "1"
		"model" "models/items/ammocrate_smg1.mdl"
	}

	"prop"
	{
		"name" "Supplies Rockets"
		"as_mdlpanel" "1"
		"model" "models/items/ammoCrate_Rockets.mdl"
	}

	"prop"
	{
		"name" "Supplies Ar2"
		"as_mdlpanel" "1"
		"model" "models/items/ammocrate_ar2.mdl"
	}

}