"Ragdolls"
{
	"page_icon"	"materials/icon16/group.png"

    "header"
    {
        "text" "Main Characters"
    }

    "image_button"
    {
        "name" "Kleiner"
        "image" "materials/entities/npc_kleiner.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/kleiner.mdl"
    }

    "image_button"
    {
        "name" "GMan"
        "image" "materials/entities/npc_gman.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/gman.mdl"
    }

    "image_button"
    {
        "name" "Breen"
        "image" "materials/entities/npc_breen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/breen.mdl"
    }

    "image_button"
    {
        "name" "Barney"
        "image" "materials/entities/npc_barney.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/barney.mdl"
    }

    "image_button"
    {
        "name" "Eli"
        "image" "materials/entities/npc_eli.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/eli.mdl"
    }

    "image_button"
    {
        "name" "Grigori"
        "image" "materials/entities/npc_monk.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/monk.mdl"
    }

    "image_button"
    {
        "name" "Alyx"
        "image" "materials/entities/npc_alyx.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/alyx.mdl"
    }

    "image_button"
    {
        "name" "Mossman"
        "image" "materials/entities/npc_mossman.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/mossman.mdl"
    }

    "image_button"
    {
        "name" "Magnusson (EP2)"
        "image" "materials/entities/npc_magnusson.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/magnusson.mdl"
    }

    "image_button"
    {
        "name" "DOG"
        "image" "materials/entities/npc_dog.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/dog.mdl"
    }

    "image_button"
    {
        "name" "Vortigaunt"
        "image" "materials/entities/npc_vortigaunt.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/vortigaunt.mdl"
    }

    "header"
    {
        "text" "The Undead/Aliens"
    }

    "image_button"
    {
        "name" "Zombie"
        "image" "materials/entities/npc_zombie.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Zombie/Classic.mdl"
    }

    "image_button"
    {
        "name" "Zombie Torso"
        "image" "materials/entities/npc_zombie.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Zombie/Classic_torso.mdl"
    }

    "image_button"
    {
        "name" "Fast Zombie"
        "image" "materials/entities/npc_fastzombie.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Zombie/Fast.mdl"
    }

    "image_button"
    {
        "name" "Fast Zombie Torso"
        "image" "materials/entities/npc_fastzombie_torso.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Gibs/Fast_Zombie_Torso.mdl"
    }

    "image_button"
    {
        "name" "Poison Zombie"
        "image" "materials/entities/npc_poisonzombie.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Zombie/Poison.mdl"
    }

    "image_button"
    {
        "name" "Zombine (EP1/2)"
        "image" "materials/entities/npc_zombine.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Zombie/zombie_soldier.mdl"
    }

    "image_button"
    {
        "name" "Headcrab"
        "image" "materials/entities/npc_headcrab.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/headcrabclassic.mdl"
    }

    "image_button"
    {
        "name" "Fast Headcrab"
        "image" "materials/entities/npc_headcrab_fast.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/headcrab.mdl"
    }

    "image_button"
    {
        "name" "Poison Headcrab"
        "image" "materials/entities/npc_headcrab_black.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/headcrabblack.mdl"
    }

    "image_button"
    {
        "name" "Antlion"
        "image" "materials/entities/npc_antlion.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/antlion.mdl"
    }

    "image_button"
    {
        "name" "Antlion Guard"
        "image" "materials/entities/npc_antlionguard.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/antlion_guard.mdl"
    }

    "header"
    {
        "text" "Humans"
    }

    "image_button"
    {
        "name" "Citizen (Male 01)"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group01/Male_01.mdl"
    }

    "image_button"
    {
        "name" "Citizen (Male 02)"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group01/Male_02.mdl"
    }

    "image_button"
    {
        "name" "Citizen (Male 03)"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group01/Male_03.mdl"
    }

    "image_button"
    {
        "name" "Citizen (Male 04)"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group01/Male_04.mdl"
    }

    "image_button"
    {
        "name" "Citizen (Male 05)"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group01/Male_05.mdl"
    }

    "image_button"
    {
        "name" "Citizen (Male 06)"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group01/Male_06.mdl"
    }

    "image_button"
    {
        "name" "Citizen (Male 07)"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group01/Male_07.mdl"
    }

    "image_button"
    {
        "name" "Citizen (Male 08)"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group01/Male_08.mdl"
    }

    "image_button"
    {
        "name" "Citizen (Male 09)"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group01/Male_09.mdl"
    }

    "image_button"
    {
        "name" "Citizen (Female 01)"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group01/Female_01.mdl"
    }

    "image_button"
    {
        "name" "Citizen (Female 02)"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group01/Female_02.mdl"
    }

    "image_button"
    {
        "name" "Citizen (Female 03)"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group01/Female_03.mdl"
    }

    "image_button"
    {
        "name" "Citizen (Female 04)"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group01/Female_04.mdl"
    }

    "image_button"
    {
        "name" "Citizen (Female 06)"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group01/Female_06.mdl"
    }

    "image_button"
    {
        "name" "Citizen (Female 07)"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group01/Female_07.mdl"
    }

    "image_button"
    {
        "name" "Refugee (Male 01)"
        "image" "materials/entities/refugee.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group02/Male_01.mdl"
    }

    "image_button"
    {
        "name" "Refugee (Male 02)"
        "image" "materials/entities/refugee.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group02/Male_02.mdl"
    }

    "image_button"
    {
        "name" "Refugee (Male 03)"
        "image" "materials/entities/refugee.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group02/Male_03.mdl"
    }

    "image_button"
    {
        "name" "Refugee (Male 04)"
        "image" "materials/entities/refugee.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group02/Male_04.mdl"
    }

    "image_button"
    {
        "name" "Refugee (Male 05)"
        "image" "materials/entities/refugee.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group02/Male_05.mdl"
    }

    "image_button"
    {
        "name" "Refugee (Male 06)"
        "image" "materials/entities/refugee.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group02/Male_06.mdl"
    }

    "image_button"
    {
        "name" "Refugee (Male 07)"
        "image" "materials/entities/refugee.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group02/Male_07.mdl"
    }

    "image_button"
    {
        "name" "Refugee (Male 08)"
        "image" "materials/entities/refugee.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group02/Male_08.mdl"
    }

    "image_button"
    {
        "name" "Refugee (Male 09)"
        "image" "materials/entities/refugee.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group02/Male_09.mdl"
    }

    "image_button"
    {
        "name" "Refugee (Female 01)"
        "image" "materials/entities/refugee.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group02/Female_01.mdl"
    }

    "image_button"
    {
        "name" "Refugee (Female 02)"
        "image" "materials/entities/refugee.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group02/Female_02.mdl"
    }

    "image_button"
    {
        "name" "Refugee (Female 03)"
        "image" "materials/entities/refugee.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group02/Female_03.mdl"
    }

    "image_button"
    {
        "name" "Refugee (Female 04)"
        "image" "materials/entities/refugee.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group02/Female_04.mdl"
    }

    "image_button"
    {
        "name" "Refugee (Female 06)"
        "image" "materials/entities/refugee.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group02/Female_06.mdl"
    }

    "image_button"
    {
        "name" "Refugee (Female 07)"
        "image" "materials/entities/refugee.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group02/Female_07.mdl"
    }

    "image_button"
    {
        "name" "Rebel (Male 01)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03/Male_01.mdl"
    }

    "image_button"
    {
        "name" "Rebel (Male 02)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03/Male_02.mdl"
    }

    "image_button"
    {
        "name" "Rebel (Male 03)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03/Male_03.mdl"
    }

    "image_button"
    {
        "name" "Rebel (Male 04)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03/Male_04.mdl"
    }

    "image_button"
    {
        "name" "Rebel (Male 05)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03/Male_05.mdl"
    }

    "image_button"
    {
        "name" "Rebel (Male 06)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03/Male_06.mdl"
    }

    "image_button"
    {
        "name" "Rebel (Male 07)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03/Male_07.mdl"
    }

    "image_button"
    {
        "name" "Rebel (Male 08)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03/Male_08.mdl"
    }

    "image_button"
    {
        "name" "Rebel (Male 09)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03/Male_09.mdl"
    }

    "image_button"
    {
        "name" "Rebel (Female 01)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03/Female_01.mdl"
    }

    "image_button"
    {
        "name" "Rebel (Female 02)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03/Female_02.mdl"
    }

    "image_button"
    {
        "name" "Rebel (Female 03)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03/Female_03.mdl"
    }

    "image_button"
    {
        "name" "Rebel (Female 04)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03/Female_04.mdl"
    }

    "image_button"
    {
        "name" "Rebel (Female 06)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03/Female_06.mdl"
    }

    "image_button"
    {
        "name" "Rebel (Female 07)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03/Female_07.mdl"
    }

    "image_button"
    {
        "name" "Medic (Male 01)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03m/Male_01.mdl"
    }

    "image_button"
    {
        "name" "Medic (Male 02)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03m/Male_02.mdl"
    }

    "image_button"
    {
        "name" "Medic (Male 03)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03m/Male_03.mdl"
    }

    "image_button"
    {
        "name" "Medic (Male 04)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03m/Male_04.mdl"
    }

    "image_button"
    {
        "name" "Medic (Male 05)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03m/Male_05.mdl"
    }

    "image_button"
    {
        "name" "Medic (Male 06)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03m/Male_06.mdl"
    }

    "image_button"
    {
        "name" "Medic (Male 07)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03m/Male_07.mdl"
    }

    "image_button"
    {
        "name" "Medic (Male 08)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03m/Male_08.mdl"
    }

    "image_button"
    {
        "name" "Medic (Male 09)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03m/Male_09.mdl"
    }

    "image_button"
    {
        "name" "Medic (Female 01)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03m/Female_01.mdl"
    }

    "image_button"
    {
        "name" "Medic (Female 02)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03m/Female_02.mdl"
    }

    "image_button"
    {
        "name" "Medic (Female 03)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03m/Female_03.mdl"
    }

    "image_button"
    {
        "name" "Medic (Female 04)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03m/Female_04.mdl"
    }

    "image_button"
    {
        "name" "Medic (Female 06)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03m/Female_06.mdl"
    }

    "image_button"
    {
        "name" "Medic (Female 07)"
        "image" "materials/entities/rebel.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Group03m/Female_07.mdl"
    }

    "image_button"
    {
        "name" "Corpse"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/corpse1.mdl"
    }

    "image_button"
    {
        "name" "Corpse 2"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Charple01.mdl"
    }

    "image_button"
    {
        "name" "Corpse 3"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Charple02.mdl"
    }

    "image_button"
    {
        "name" "Corpse 4"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Charple03.mdl"
    }

    "image_button"
    {
        "name" "Corpse 5"
        "image" "materials/entities/npc_citizen.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Humans/Charple04.mdl"
    }

    "header"
    {
        "text" "The Combine"
    }

    "image_button"
    {
        "name" "Combine Soldier"
        "image" "materials/entities/npc_combine_s.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/combine_soldier.mdl"
    }

    "image_button"
    {
        "name" "Elite Combine"
        "image" "materials/entities/combineelite.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/combine_Super_Soldier.mdl"
    }

    "image_button"
    {
        "name" "Prison Guard"
        "image" "materials/entities/combineprison.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Combine_Soldier_PrisonGuard.mdl"
    }

    "image_button"
    {
        "name" "Metropolice"
        "image" "materials/entities/npc_metropolice.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/police.mdl"
    }

    "image_button"
    {
        "name" "Manhack"
        "image" "materials/entities/npc_manhack.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/manhack.mdl"
    }

    "image_button"
    {
        "name" "Combine Scanner"
        "image" "materials/entities/npc_cscanner.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Combine_Scanner.mdl"
    }

    "image_button"
    {
        "name" "Hunter (EP2)"
        "image" "materials/entities/npc_hunter.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/hunter.mdl"
    }

    "image_button"
    {
        "name" "Strider"
        "image" "materials/entities/npc_strider.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/combine_strider.mdl"
    }

    "image_button"
    {
        "name" "Gunship"
        "image" "materials/entities/npc_combinegunship.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/gunship.mdl"
    }

    "image_button"
    {
        "name" "Combine Dropship"
        "image" "materials/entities/npc_combinegunship.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Combine_dropship.mdl"
    }

    "header"
    {
        "text" "Birds"
    }

    "image_button"
    {
        "name" "Crow"
        "image" "materials/entities/npc_crow.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/Crow.mdl"
    }

    "image_button"
    {
        "name" "Pigeon"
        "image" "materials/entities/npc_pigeon.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/pigeon.mdl"
    }

    "image_button"
    {
        "name" "Seagull"
        "image" "materials/entities/npc_seagull.png"
        "command" "prop_physics_create props_junk/wood_crate001a.mdl;ent_setname fixpos;wait;ent_remove fixpos;ent_create prop_ragdoll model models/seagull.mdl"
    }

}